### ISSUE TITLE
Script d'intégration sur une source de données, permettant d'ajouter des applications

### ISSUE THREAD

**Issue by Carolinedanslesnuages** [dnum-mi/referentiel-applications#18]
Faire un script qui permet d’intégrer la donnée depuis un fichier json dans le referentiel
curl -X 'GET' \
  'https://canel2-1-backend.dev.numerique-interieur.com/api/global-search?query=%2A' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUFBMSSIsIm5hbWUiOiJEU08iLCJpYXQiOjE1MTYyMzkwMjJ9.hBob79fE97VlChR27KFFjTn22OEoEy202TotgfNvntU'

@CMentG voici le script que tu peux écrire sur un editeur comme VSCode   (Je peux te montrer si tu veux )

```
#!/bin/bash

# Le chemin vers le fichier JSON
FILE_PATH="data.json"

# L'URL de l'endpoint API
API_URL="https://your-api-endpoint.com/api"

# Le token d'authentification
AUTH_TOKEN="your_auth_token"

# Envoyer le fichier JSON en utilisant curl avec le token d'authentification
RESPONSE=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}" -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${AUTH_TOKEN}" --data "@${FILE_PATH}" "${API_URL}")

# Extraire le code de statut HTTP de la réponse
HTTP_STATUS_CODE=$(echo "${RESPONSE}" | grep "HTTP_STATUS_CODE" | awk -F: '{print $2}')

# Extraire le corps de la réponse
RESPONSE_BODY=$(echo "${RESPONSE}" | sed -e 's/HTTP_STATUS_CODE\:.*//g')

# Afficher le code de statut HTTP et le corps de la réponse
echo "HTTP Status Code: ${HTTP_STATUS_CODE}"
echo "Response Body: ${RESPONSE_BODY}"

```

```
chmod +x send_json_to_api.sh
./send_json_to_api.sh
```

**Comment by CMentG** [comment]
Curl à faire pour mettre dans la chaine de déploiement

**Comment by Carolinedanslesnuages** [comment]
Le curl fonctionne pour le GET sur le noémi , pas pour le poste problème d'autorisation.

**Comment by CMentG** [comment]
Initialisation directement avec l'API et du JSON
